export class State {

    constructor(public Identifier: number,
        public Abbreviation: string,
        public Name: string) { }
}

export const STATES: State[] = [ 
    new State(0, 'None', 'None'),
    new State(1, 'AL', 'Alabama'),
    new State(2, 'AK', 'Alaska'),
    new State(3, 'AZ', 'Arizona'),
    new State(4, 'AR', 'Arkansas'),
    new State(5, 'CA', 'California'),
    new State(6, 'CO', 'Colorado'),
    new State(7, 'CT', 'Connecticut'),
    new State(8, 'DE', 'Delaware'),
    new State(9, 'FL', 'Florida'),
    new State(10, 'GA', 'Georgia'),
    new State(11, 'HI', 'Hawaii'),
    new State(12, 'ID', 'Idaho'),
    new State(13, 'IL', 'Illinois'),
    new State(14, 'IN', 'Indiana'),
    new State(15, 'IA', 'Iowa'),
    new State(16, 'KS', 'Kansas'),
    new State(17, 'KY', 'Kentucky'),
    new State(18, 'LA', 'Louisiana'),
    new State(19, 'ME', 'Maine'),
    new State(20, 'MD', 'Maryland'),
    new State(21, 'MA', 'Massachusetts'),
    new State(22, 'MI', 'Michigan'),
    new State(23, 'MN', 'Minnesota'),
    new State(24, 'MS', 'Mississippi'),
    new State(25, 'MO', 'Missouri'),
    new State(26, 'MY', 'Montana'),
    new State(27, 'AK', 'Nebraska'),
    new State(28, 'NV', 'Nevada'),
    new State(29, 'NH', 'New Hampshire'),
    new State(30, 'NJ', 'New Jersey'),
    new State(31, 'NM', 'New Mexico'),
    new State(32, 'NY', 'New York'),
    new State(33, 'NC', 'North Carolina'),
    new State(34, 'ND', 'North Dakota'),
    new State(35, 'OH', 'Ohio'),
    new State(36, 'OK', 'Oklahoma'),
    new State(37, 'OR', 'Oregon'),
    new State(38, 'PA', 'Pennsylvania'),
    new State(39, 'RI', 'Rhode Island'),
    new State(40, 'SC', 'South Carolina'),
    new State(41, 'SD', 'South Dakota'),
    new State(42, 'TN', 'Tennessee'),
    new State(43, 'TX', 'Texas'),
    new State(44, 'UT', 'Utah'),
    new State(45, 'VT', 'Vermont'),
    new State(46, 'VA', 'Virginia'),
    new State(47, 'WA', 'Washington'),
    new State(48, 'DC', 'Washington D.C.'),
    new State(49, 'WV', 'West Virginia'),
    new State(50, 'WI', 'Wisconsin'),
    new State(51, 'WY', 'Wyoming')
];